version: '3'
services: 
    frontend:
        restart: always
        image: konradkleine/docker-registry-frontend:v2
        ports:
            - 8080:80
        volumes:
          - ./certs/frontend.crt:/etc/apache2/server.crt:ro
          - ./certs/frontend.key:/etc/apache2/server.key:ro
        environment:
            - ENV_DOCKER_REGISTRY_HOST=192.168.137.100
            - ENV_DOCKER_REGISTRY_PORT=5000

