FROM wjn0918/ubuntu-jdk1.8
LABEL maintainer="jnW"
ADD visualis-server.tar.gz /usr/local
RUN rm -f /usr/local/*.tar.gz
WORKDIR /usr/local/visualis-server/
CMD [ "./bin/start-visualis-server.sh" ]

行政一审_案件结案信息
行政二审_案件结案信息
行政再审_案件结案信息
其他行政_结案信息
行政一审_收案信息
行政二审_收案信息
行政再审_收案信息
其他行政_收案信息

民事一审_案件结案信息
民事二审_案件结案信息
民事再审_案件结案信息
其他民事_结案信息
民事一审_收案信息
民事二审_收案信息
民事再审_收案信息
其他民事_收案信息


刑事二审_案件结案信息
刑事再审_案件结案信息
其他刑事_结案信息

刑事二审_收案信息
刑事再审_收案信息
其他刑事_收案信息

刑事一审_收案信息
刑事一审_案件结案信息

民事一审_收案信息
民事一审_案件结案信息

行政一审_收案信息
行政一审_案件结案信息