version: '3'
services: 
  eureka:
    restart: always
    image: wjn0918/webank-linkis:eureka
    container_name: eureka
    ports: 
        - 20303:20303
    extra_hosts:
        - "eureka.fd.com:192.168.137.60"
    volumes: 
        - /usr/local/linkis/eureka/logs:/usr/local/eureka/logs
        # - /usr/local/linkis/eureka/conf:/usr/local/eureka/conf