cs: 测试
onion_encry_passwd: '{{ ''123456'' | password_hash(''sha512'') }}'
onion_group: onion
onion_group_id: 5555
onion_passwd: 123456
onion_user: onion
onion_user_id: 5555
cluster:
  cluster_data_path:
  - /data/disk_01
  cluster_data_root_path: /data
  cluster_default_data_path: /data/disk_01
  cluster_path: /home/{{ onion_user }}/cluster
pkgs_path: '/tmp/pkgs'
jdk_version: 1.8.0_91
ntp_server:
  host: 192.168.50.4
docker:
  dir: docker
  tar: '{{pkgs_path}}/docker.{{ os }}.tar.gz'