version: '3'
services: 
  linkis-ujes-jdbc-entrance:
    restart: always
    image: linkis-ujes-jdbc-entrance
    container_name: linkis-ujes-jdbc-entrance
    ports: 
        - 9111:9111
    extra_hosts:
        - "eureka.fd.com:192.168.137.60"
    volumes: 
        - /usr/local/linkis/linkis-ujes-jdbc-entrance/logs:/usr/local/linkis-ujes-jdbc-entrance/logs