version: '3'
services: 
  web:
    restart: always
    image: tomcat
    container_name: web
    ports: 
      - 8080:8080
    volumes:
      - /usr/local/docker/tomcat/ROOT:/usr/local/tomcat/webapps/ROOT

