- name: 部署mysql
  hosts: mysql
  vars:
    custom_passwd: "123456"
  tasks:
    - name: 移除mariadb
      yum: 
        name: mariadb-libs-*.el7.x86_64
        state: absent
    - name: 解压mysql安装包
      unarchive:
        src: /root/mysql.tar.gz
        dest: /tmp/install/
    - name: 添加mysql本地yum源
      yum_repository:
        name: mysql 
        description: mysql YUM repo
        baseurl: file:///tmp/install/mysql
    - name: 安装mysql
      command: yum install -y --nogpgcheck mysql mysql-community-server
    - name: 启动mysql
      command: systemctl start mysqld
    - name: 获取mysql初始化密码
      shell: "cat /var/log/mysqld.log | grep root@localhost | awk -F 'root@localhost: ' '{print $2}'"
      register: passwd
    - name: 重置mysql管理员密码
      command: "mysql --connect-expired-password -u root -e \"
                ALTER USER USER() IDENTIFIED BY 'Wjn@@1234';
                set global validate_password_policy=0;
                set global validate_password_length=1;
                set global validate_password_mixed_case_count=0;
                set global validate_password_number_count=3;
                ALTER USER USER() IDENTIFIED BY '{{ custom_passwd }}';
                grant all on *.* to root@'%' identified by '{{ custom_passwd }}' with grant option;
                flush privileges;
                \""
      environment: 
        MYSQL_PWD: "{{passwd.stdout}}"
- name: 部署docker
  hosts: docker
  tags:
    - docker
  tasks:
    - name: 解压docker安装包
      unarchive:
        src: /root/docker.tar.gz
        dest: /tmp/install/
    - name: 添加docker本地yum源
      yum_repository:
        name: docker 
        description: docker YUM repo
        baseurl: file:///tmp/install/docker
    - name: 安装docker
      command: yum install -y --nogpgcheck docker
    - name: 启动docker
      command: systemctl start docker
- name: 部署nginx
  hosts: nginx
  tags:
    - nginx
  tasks:
    - name: 解压nginx安装包
      unarchive:
        src: /root/nginx.tar.gz
        dest: /tmp/install/
    - name: 添加nginx本地yum源
      yum_repository:
        name: nginx 
        description: nginx YUM repo
        baseurl: file:///tmp/install/nginx
    - name: 安装nginx
      command: yum install -y --nogpgcheck nginx
    - name: 启动nginx
      command: systemctl start nginx
- name: 安装redis
  hosts: redis
  tags:
    - redis
  tasks:
    # - name: 加载redis到docker
    - name: 启动redis
      command: "docker run -itd --name redis-test -p 6379:6379 redis"
     


    
