version: '3'
services: 
  oracle:
    restart: always
    image: registry.cn-hangzhou.aliyuncs.com/helowin/oracle_11g
    container_name: oracle
    ports: 
        - 1521:1521
    network_mode: "host"
      volumes: 
        -  ./dockerOracleData:/dockerOracleData