version: '3'
services: 
  linkis-ujes-python-entrance:
    restart: always
    image: linkis-ujes-python-entrance
    container_name: linkis-ujes-python-entrance
    ports: 
        - 9110:9110
    extra_hosts:
        - "eureka.fd.com:192.168.137.60"
    volumes: 
        - /usr/local/linkis/linkis-ujes-python-entrance/logs:/usr/local/linkis-ujes-python-entrance/logs