- name: pam_limits
  pam_limits: >
    backup=yes
    domain=*
    limit_type='-'
    limit_item={{ item }}
    value=602400
  with_items:
    - nproc
    - nofile

- name: close firewalld
  service: name=firewalld.service state=stopped enabled=no
  ignore_errors: true

- name: close iptables
  service: name=iptables state=stopped enabled=no
  ignore_errors: true

- name: disabled selinux
  selinux: state=disabled
  ignore_errors: true

- name: LANG modify zh_CN.UTF-8
  lineinfile:
     backup: yes
     dest: /etc/locale.conf
     regexp: '^LANG='
     line: 'LANG=zh_CN.UTF-8'
  ignore_errors: true

- name: set default random port
  shell: echo -e "\nnet.ipv4.ip_local_port_range = 32768 60999" >> /etc/sysctl.conf
  ignore_errors: true
<<<<<<< HEAD

=======
<<<<<<< HEAD

=======
>>>>>>> c45965e0bfbe39c772db5a5451f4f20dd2559fb6
>>>>>>> 624fd980f684d7ca40226c2d4cbc84736862754d
