- name: create hosts
  template: src=hosts.j2 dest=/tmp/hosts.onion
  delegate_to: 127.0.0.1 # 任务委派
  run_once: true

- name: update /etc/hosts
  blockinfile:
    dest: /etc/hosts
    backup: yes
    state: present
    block: "{{ lookup('file', '/tmp/hosts.onion') }}"
