- name: install java
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - java-1.8.0-openjdk.x86_64 
    - java-1.8.0-openjdk-demo 
    - java-1.8.0-openjdk-devel 
    - java-1.8.0-openjdk-javadoc 
