version: '3'
services: 
  hadoop:
    restart: always
    image: hadoop
    container_name: hadoop
    ports: 
        - 9005:9005
    extra_hosts:
        - "master:192.168.137.10"
    volumes: 
        # - ./bin:/hadoop-3.1.3/bin
        # - ./bin:/hadoop-3.1.3/etc
        