- name: 上传java{{java.version}}安装包
  unarchive:
    src: "{{ java.tar }}"
    dest: '/var/www/html'
- name: 上传cdh安装包
  unarchive:
    src: "{{ cdh.tar }}"
    dest: '/var/www/html'
- name: 安装jdk1.8
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - java-1.8.0-openjdk.x86_64 
    - java-1.8.0-openjdk-demo 
    - java-1.8.0-openjdk-devel 
    - java-1.8.0-openjdk-javadoc 
