server:
    port: 9004
  spring:
    application:
      name: dss-server
  
  
  eureka:
    client:
      serviceUrl:
        defaultZone: http://eureka.fd.com:20303/eureka/
    instance:
      prefer-ip-address: true
      ip-address: 192.168.137.60
      metadata-map:
        test: wedatasphere
  
  management:
    endpoints:
      web:
        exposure:
          include: refresh,info
  logging:
    config: classpath:log4j2.xml
  