version: '3'
services: 
  dss:
    restart: always
    image: dss
    container_name: dss
    ports: 
        - 9004:9004
    extra_hosts:
        - "eureka.fd.com:192.168.137.60"
    volumes: 
        # - ./conf:/usr/local/dss-server/conf
        - ./logs:/usr/local/dss-server/logs
        