version: '3'
services: 
  oracle:
    restart: always
    image: postgres:10.0
    container_name: postgres
    ports: 
        - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    network_mode: "host"
      # volumes: 
      #   -  ./dockerOracleData:/dockerOracleData