未验证

docker run -p 8080:8080 -p 50000:50000 -v /your/home:/var/jenkins_home jenkins
version: '3.7'

services:
  jenkins:
    hostname: jenkins
    # 启动容器名称mysql
    container_name: jenkins
    # 使用mysql 5.7.20的镜像
    image: jenkins
    # 自启动
    restart: always
    command:
      # mysql默认使用utf8mb4编码
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
      # mysql时间加8个小时
      - --default-time_zone=+8:00
    environment:
      # 服务器时区使用上海 
      TZ: Asis/Shanghai
      # mysql初始化密码
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      # 容器3306端口映射到宿主机3306端口
      - "50000:50000"
      - "9090:8080"
    volumes:
      # mysql相关数据存储在宿主机/data/docker/mysql文件夹
      - /var/lib/jenkins:/var/jenkins_home 
    privileged: true