
# mkdir /var/lib/jenkins/
# chown -R 1000:1000 /var/lib/jenkins/
version: '3.7'

services:
  jenkins:
    hostname: jenkins
    container_name: jenkins
    image: jenkins/jenkins:2.257-centos7
    # 自启动
    restart: always
    ports:
      - "50000:50000"
      - "9090:8080"
    volumes:
      - /var/lib/jenkins:/var/jenkins_home 
    privileged: true