
# mkdir /var/lib/jenkins/
# chown -R 1000:1000 /var/lib/jenkins/
version: '3.7'

services:
  jenkins:
    hostname: jenkins
    container_name: jenkins
    image: jenkins
    # 自启动
    restart: always
    ports:
      # 容器3306端口映射到宿主机3306端口
      - "50000:50000"
      - "9090:8080"
    volumes:
      # mysql相关数据存储在宿主机/data/docker/mysql文件夹
      - /var/lib/jenkins:/var/jenkins_home 
    privileged: true